- CONTRIBUTING.md
- docs/AnOverviewOfConsensus.md
- docs/GitProcess.md
- docs/ProfilingTipsAndTricks.md
- docs/References.md
Thanks to [`xrefcheck`](https://github.com/serokell/xrefcheck) I found these broken links.
> Fix some links on the documents

- CONTRIBUTING.md
Fixes https://github.com/input-output-hk/ouroboros-network/issues/4323
> Add our documentation policy to CONTRIBUTING

- docs/ReleaseProcess.md
We now rely on the scripts created in https://github.com/input-output-hk/ouroboros-network/pull/4433/files
> Update the instructions for cutting a release

- docs/HardWonWisdom.md
Added an answer to "Why use the Honest Chain Growth window as the Ledger's Stability Window?"
> HardWordWidsom.md: relate HCG and Stability Window

- .github/workflows/pages.yml
There was a typo in the directory
> Fix pages directory

- .github/workflows/pages.yml
- .gitignore
- cabal.project.local.github-pages
Forcing the orphan branch should result in the `gh-pages` branch being pruned. Same as in https://github.com/input-output-hk/ouroboros-network/pull/4535
> Force orphan branch for gh-pages

- flake.lock
...also bumps our nixpkgs pin transitively.
> Bump haskell.nix pin

- docs/website/docs/HardWonWisdom.md
- ouroboros-consensus-cardano/src/cardano-testlib/Test/ThreadNet/Infra/ShelleyBasedHardFork.hs
- ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/CanHardFork.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/ShelleyHFC.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/HardFork/Combinator.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Ledger.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/State/Types.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Translation.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/HardFork/Forecast.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/HardFork/History.hs
Also closes #80 (I did not rename `EraTranslation` so far)
> HardWonWisdom.md: overview of cross-era forecasting 

- docs/website/docs/HardWonWisdom.md
Added an answer to "Which slots/times/epochs can we translate?"
> HardWordWidsom.md: spell out the forecast horizon

- .github/workflows/ci.yml
- ouroboros-consensus/ouroboros-consensus.cabal
Changed install of `lmdb-dev` to `liblmdb-dev`, fixed an `s-r-p` and formatted cabal files.
> Fix failing install of system dependencies in GitHub actions

- cabal.project
- flake.lock
- ouroboros-consensus-diffusion/changelog.d/20230605_105710_joris_fs_sim_bump_0_2.md
- ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
- ouroboros-consensus/changelog.d/20230605_105616_joris_fs_sim_bump_0_2.md
- ouroboros-consensus/ouroboros-consensus.cabal
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ImmutableDB/StateMachine.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/VolatileDB/StateMachine.hs
> Bump `fs-sim` dependency to `>= 0.2`

- ouroboros-consensus/changelog.d/20230612_093445_alexander.esgen_iolike_catch_stm.md
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/EarlyExit.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/IOLike.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/BlockchainTime/Simple.hs
Supersedes and closes https://github.com/input-output-hk/ouroboros-network/pull/4147, closes https://github.com/input-output-hk/ouroboros-network/issues/1461.
> Include `MonadCatch (STM m)` in `IOLike m`

- ouroboros-consensus-cardano/changelog.d/20230530_105533_alexander_call_cryptoinit.md
- ouroboros-consensus-cardano/changelog.d/20230530_185109_alexander_ensure_defaultmainwithtestenv.md
- ouroboros-consensus-cardano/changelog.d/20230530_185118_alexander_call_cryptoinit.md
- ouroboros-consensus-cardano/changelog.d/20230530_185127_alexander_call_cryptoinit.md
- ouroboros-consensus-cardano/changelog.d/20230602_175722_joris_rename_strictmvar_strictsvar.md
- ouroboros-consensus-cardano/changelog.d/20230621_143811_fraser_new_ledger.md
- ouroboros-consensus-diffusion/changelog.d/20230524_174543_alexander_graphviz_lower_bound.md
- ouroboros-consensus-diffusion/changelog.d/20230530_085153_marcin_ouroboros_network_bound.md
- ouroboros-consensus-diffusion/changelog.d/20230614_135851_damian_update_comment_forkblockforging.md
- ouroboros-consensus-protocol/changelog.d/20230602_175722_joris_rename_strictmvar_strictsvar.md
- ouroboros-consensus/changelog.d/20230525_122032_alexander_remove_cardano_ledger_binary_dependency.md
- ouroboros-consensus/changelog.d/20230530_185118_alexander_call_cryptoinit.md
- ouroboros-consensus/changelog.d/20230531_103217_fraser_force_strictmvar.md
- ouroboros-consensus/changelog.d/20230605_113247_damian_mempool_benchmarks.md
Add (partially-autogenerated) changelog fragments for all changes since last release
> Add (partially-autogenerated) changelog fragments for all changes since last release

- CONTRIBUTING.md
... and add a rule for updating dependencies bounds.
> Add a quick reference section to CONTRIBUTING.md

- docs/website/contents/about-ouroboros/References.md
Numerous people found this table very useful so far; let us make it a bit easier to discover.
> Docs: add link to the Cardano feature table from CIP-0059

- ouroboros-consensus-cardano/README.md
- ouroboros-consensus-cardano/app/immdb-server.hs
Based on feedback by @jasagredo
> ImmDB server: improve docs

- cabal.project
- flake.lock
- ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
See https://github.com/input-output-hk/cardano-haskell-packages/pull/375/commits/5109d7ad7dbf309d6f19cd0c0ced2eba8005c79f
> Mirror CHaP revision for cardano-ledger-conway-1.6

- .github/workflows/cabal.project.local
See https://github.com/input-output-hk/ouroboros-consensus/pull/159#discussion_r1241898173
> Incorporate feedback from PR #159

- ouroboros-consensus-cardano/src/byron-testlib/Test/Consensus/Byron/Generators.hs
- ouroboros-consensus-cardano/test/cardano-test/Test/Consensus/Cardano/Translation.hs
> Test Cardano translations with an empty UTxO

- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Types.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/BackingStore.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/BackingStore/InMemory.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/BackingStore/Init.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/BackingStore/LMDB.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Impl.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Types.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/OnDisk.hs
Do this in consensus instead of polluting the tracing code too much with low level stuff. 
Part of #227
> Trace backing store events

- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Inspect.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/ShelleyHFC.hs
- ouroboros-consensus/changelog.d/20230719_174819_alexander.esgen_shelley_protocol_updates.md
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util.hs
> Minor tweaks in Shelley HFC protocol updates logic

- ouroboros-consensus-cardano/src/tools/Cardano/Tools/DBAnalyser/Analysis.hs
- ouroboros-consensus/bench/mempool-bench/Bench/Consensus/MempoolWithMockedLedgerItf.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/DbChangelog.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/DbChangelog/Update.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Impl.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/Model.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/InMemory.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/OnDisk.hs
Adds some examples and clarifications.
Closes #209
> DbChangelog haddocks

- CONTRIBUTING.md
> Revision policy: prefer additive version bound changes

- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Tables/DiffSeq.hs
> Add comment about EBBs to `noSlotBoundsIntersect`

- cabal.project
- ouroboros-consensus-cardano-legacy-block/ouroboros-consensus-cardano-legacy-block.cabal
- ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
- ouroboros-consensus-cardano/src/cardano-testlib/Test/ThreadNet/Infra/ShelleyBasedHardFork.hs
- ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/CanHardFork.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Eras.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/ShelleyHFC.hs
- ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/HardFork/Combinator.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Ledger.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/State/Types.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Translation.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Tables.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Tables/DiffSeq.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Tables/MapKind.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Tables/Utils.hs
> Upgrade UTxO-HD to Conway 1.6

- .github/workflows/cabal.project.local
- .github/workflows/ci.yml
- cabal.project
- flake.lock
- nix/haskell.nix
- ouroboros-consensus-cardano-legacy-block/ouroboros-consensus-cardano-legacy-block.cabal
- ouroboros-consensus-cardano-legacy-block/src/Legacy/Cardano/CanHardFork.hs
- ouroboros-consensus-cardano/src/cardano-testlib/Test/ThreadNet/Infra/ShelleyBasedHardFork.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/ShelleyHFC.hs
- ouroboros-consensus-cardano/src/tools/Cardano/Tools/DBTruncater/Run.hs
- ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
- ouroboros-consensus/bench/mempool-bench/Bench/Consensus/Mempool/Params.hs
- ouroboros-consensus/bench/mempool-bench/Bench/Consensus/Mempool/Scenario.hs
- ouroboros-consensus/src/consensus-testlib/Test/Util/QuickCheck.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Block/RealPoint.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Basics.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Dual.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Extended.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Tables.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Tables/Common.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/DbChangelog/Query.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/DbChangelog/Update.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Impl.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Query.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Update.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/EarlyExit.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/BlockchainTime/Simple.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/BackingStore.hs
- scripts/ci/run-stylish.sh
Upgrade code on UTxO-HD branch for GHC 9.6
> Upgrade code to GHC 9.6

- docs/utxo-hd/v0.1/for-public.md
> Add documentation for the general public

- .github/workflows/ci.yml
- .github/workflows/documentation.yml
- docs/website/package-lock.json
- docs/website/package.json
- docs/website/yarn.lock
> Update website dependencies

- docs/utxo-hd/v0.1/for-developers.md
> UTxO-HD for-developers documentation

- docs/website/contents/for-developers/BootstrapPeersIER.md
- docs/website/sidebars.js
> docs: draft BootstrapPeers IER

- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node/Tracers.hs
- ouroboros-consensus/src/consensus-testlib/Test/Util/ChainDB.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Args.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Args.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/BackingStore/Init.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Impl.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Types.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/LocalStateQuery/Server.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/OnDisk.hs
Create a new tracer to provide for the backing store events.
> Isolate the backing-store tracing

- ouroboros-consensus-cardano-legacy-block/src/Legacy/LegacyBlock.hs
- ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
- ouroboros-consensus-cardano/src/byronspec/Ouroboros/Consensus/ByronSpec/Ledger/Mempool.hs
- ouroboros-consensus-cardano/src/shelley-testlib/Test/ThreadNet/TxGen/Shelley.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Mempool.hs
- ouroboros-consensus-cardano/test/byron-test/Test/ThreadNet/DualByron.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/HardFork/Combinator/A.hs
- ouroboros-consensus/bench/mempool-bench/Bench/Consensus/Mempool/TestBlock.hs
- ouroboros-consensus/src/mock-block/Ouroboros/Consensus/Mock/Ledger/Block.hs
- ouroboros-consensus/src/ouroboros-consensus/Data/SOP/Functors.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/InjectTxs.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Ledger/Query.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Mempool.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Dual.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Query.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/SupportsMempool.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Impl/Common.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Query.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Update.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/LocalStateQuery/Server.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/Mempool.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/Mempool/StateMachine.hs
> Avoid HF projections in mempool

- cabal.project
- ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
- ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/Node.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Node/TPraos.hs
- ouroboros-consensus-cardano/src/unstable-cardano-testlib/Test/Consensus/Cardano/ProtocolInfo.hs
- ouroboros-consensus-cardano/src/unstable-cardano-testlib/Test/ThreadNet/Infra/ShelleyBasedHardFork.hs
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Node/Protocol/Cardano.hs
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Block/Cardano.hs
- ouroboros-consensus-cardano/test/cardano-test/Test/ThreadNet/AllegraMary.hs
- ouroboros-consensus-cardano/test/cardano-test/Test/ThreadNet/MaryAlonzo.hs
- ouroboros-consensus-cardano/test/cardano-test/Test/ThreadNet/ShelleyAllegra.hs
This is actually what I envisioned for the EraTransiton interface from ledger.
> Switch to using TransitionContext everywhere during initialization

- flake.nix
- nix/ci.nix
- nix/haskell.nix
- ouroboros-consensus-cardano/README.md
See the new `ouroboros-consensus-cardano` README paragraph
> Build db-analyser and friends without asserts for more GHC versions

- docs/website/contents/for-developers/HardWonWisdom.md
> HardWonWisdom.md: bugfix in HFC time-translation explanation

- docs/website/contents/for-developers/HardWonWisdom.md
We're still working through the most subtle parts, but this seems like a broadly useful artifact to end up with.
Also see the single commit's message.
> HardWonWisdom: the HFC interface

- flake.nix
Fixup for https://github.com/input-output-hk/ouroboros-consensus/pull/379, see the commit message
> Re-add line accidentally removed in #379

- ouroboros-consensus/changelog.d/20231004_120651_alexander.esgen_export_HardForkSelectView.md
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Protocol.hs
Needed to actually make use of #384 in node.
> Export `HardForkSelectView`

- ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/PeerSimulator/Run.hs
This PR removes ConnectionThread and replaces the use async with forkLinkedThread
> Remove the ConnectionThread data type

- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule.hs
I rearranged the functions a bit and cleaned up some glaring peculiarites, hope that doesn't make it too hard to review
> add docs for PointSchedule

- CONTRIBUTING.md
- flake.lock
- flake.nix
- nix/shell.nix
- nix/tools.nix
- scripts/docs/haddocks.sh
> Add `cabal-docspec` to the Nix shell 

- ouroboros-consensus-cardano-legacy-block/src/Legacy/LegacyBlock.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Ledger.hs
- ouroboros-consensus-cardano/src/tools/Cardano/Tools/DBSynthesizer/Forging.hs
- ouroboros-consensus-diffusion/src/diffusion-testlib/Test/ThreadNet/Network.hs
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Block/Forging.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Forging.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Ledger.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Mempool.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/SupportsMempool.hs
- ouroboros-consensus/src/tutorials/Ouroboros/Consensus/Tutorial/Simple.lhs
> Remove unused NoThunks constraint, specialize mk in BlockForging

- ouroboros-consensus-diffusion/CHANGELOG.md
Fixes a mistaken version in changelog, apologies for that.
> Fix changelog entry for diffusion

- ouroboros-consensus-cardano-legacy-block/ouroboros-consensus-cardano-legacy-block.cabal
- ouroboros-consensus-cardano-legacy-block/src/Legacy/Convert.hs
- ouroboros-consensus/ouroboros-consensus.cabal
- ouroboros-consensus/src/ouroboros-consensus/Data/SOP/Match.hs
- ouroboros-consensus/src/ouroboros-consensus/Data/SOP/OptNP.hs
`HTrans` instances for `Mismatch` and `OptNP`, which we'll need later for #344
> A few `HTrans` instances

- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/BlockTree.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup/GenChains.hs
`TestBlock`'s constructor `firstBlock` hardcodes the slot number to 1. While this is not illegal, it does map the chain generator's slots incorrectly.
> Set the first slot number to 0 when generating Genesis test chains

- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/LongRangeAttack.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
We match on the `ThreadKilled` exception to classify a peer's termination for later use with the Genesis governor. Right now we only include the information in the output.
> Observe that peers were killed during a point schedule test

- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Resources.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
This requires us to pass around the candidate fragments as a TVar of TVars.
This will become more significant in terms of code duplication once the governor is merged.
> Use `bracketChainSync` in the peer simulator

- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
Threads aren't killed anymore unless something notable happens – in which case we might actually want to retain that information, especially once we add the governor.
> Remove obsolete exception filter in runPointSchedule

- cabal.project
- ouroboros-consensus-diffusion/changelog.d/jasagredo_timeouts.md
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
Also set the index state so that we don't need the constraint for nothunks
> Make `srnChainSyncTimeout` monadic

- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/LongRangeAttack.hs
This is only to experiment with better performance for development. It still idles about 60% of the time because we're using static threadDelay instead of waiting for completion of the clients.
> Add flag to LongRangeAttack for running in IO

- docs/website/contents/for-developers/ReleaseProcess.md
> ReleaseProcess.md: add a simple tip

- ouroboros-consensus/ouroboros-consensus.cabal
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/API.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/API/DiskPolicy.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/BackingStore.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/DbChangelog.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Common.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Flush.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Forker.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Init.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Snapshots.hs
> UTxO-HD: LedgerDB API rewrite and V1 implementation

- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/BlockTree.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule.hs
Spin-off of https://github.com/input-output-hk/ouroboros-consensus/pull/817 containing only the printing part.
> Improve pretty printing of various items

- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/LongRangeAttack.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Tests/Rollback.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Tests/Timeouts.hs
Reimplementation of #496 targetting #819, which include the more general changes of #500.
> Adjust number of test cases

- ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/StateDiagram.hs
> Add a pretty-printer for the current state of the node under test

- cabal.project
- ouroboros-consensus/ouroboros-consensus.cabal
- ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/RefEnv.hs
- ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/ToExpr.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/ResourceRegistry.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/StateMachine.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ImmutableDB/StateMachine.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/OnDisk.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/VolatileDB/StateMachine.hs
Implement QSM's CanDiff via tree-diff
> Implement QSM's `CanDiff` via `tree-diff`

- .github/workflows/hlint.yml
- .gitignore
- .hlint.yaml
- ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/ChainSync/Client.hs
Add HLint to CI, and add an initial .hlint.yaml file.
> Add hlint to CI and an initial .hlint.yaml file

- cabal.project
- flake.lock
- flake.nix
- ouroboros-consensus/ouroboros-consensus.cabal
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/Unit.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/BackingStore.hs
> Bump `quickcheck-lockstep` to `>= 0.3`

- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Eras.hs
simplify the `isValid` handling in `applyAlonzoBasedTx` so we're no longer negating `Bool`s quite as much
> simplify the code handling ValidationTagMismatch and Alonzo-onwards transactions' isValid flags

- docs/website/contents/for-developers/HardWonWisdom.md
I studied this section again for the current HFC questions we're considering, and I noticed these improvements.
> Some HardWonWisdom.md updates related to HFC

- .github/PULL_REQUEST_TEMPLATE.md
... in our pull request template.
> Write down expectations about tests in PRs

- ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/Node.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Node/TPraos.hs
> Integrate DReps and initial delegates injection

- .github/workflows/ci.yml
- .github/workflows/documentation.yml
- cabal.project
- flake.lock
- ouroboros-consensus-cardano/changelog.d/20240129_115458_javier.sagredo_ghc_9_8.md
- ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Mempool.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Node/Praos.hs
- ouroboros-consensus-cardano/src/unstable-cardano-testlib/Test/Consensus/Cardano/Examples.hs
- ouroboros-consensus-diffusion/changelog.d/20240129_115203_javier.sagredo_ghc_9_8.md
- ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Network/NodeToClient.hs
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node/ExitPolicy.hs
- ouroboros-consensus-diffusion/src/unstable-diffusion-testlib/Test/ThreadNet/Util/NodeJoinPlan.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/BlockTree.hs
- ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
- ouroboros-consensus/changelog.d/20240129_115103_javier.sagredo_ghc_9_8.md
- ouroboros-consensus/ouroboros-consensus.cabal
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Forging.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Basics.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/LocalStateQuery/Server.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Protocol/PBFT.hs
- ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/Range.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/LocalStateQuery/Server.hs
- ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/Adversarial.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ImmutableDB/Primary.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/OnDisk.hs
- sop-extras/sop-extras.cabal
- strict-sop-core/strict-sop-core.cabal
> Make to build with ghc-9.8

- docs/website/contents/about-ouroboros/index.md
... in the "About Ouroboros" section.
> Reword the high-level motivation

- docs/website/contents/for-developers/AbstractProtocol.md
- docs/website/contents/for-developers/AddingAnEra.md
- docs/website/contents/for-developers/ChainSync.md
- docs/website/contents/for-developers/HardWonWisdom.md
- ouroboros-consensus/src/unstable-tutorials/Ouroboros/Consensus/Tutorial/Simple.lhs
- ouroboros-consensus/src/unstable-tutorials/Ouroboros/Consensus/Tutorial/WithEpoch.lhs
This PR updates some outdated links and filenames in the documentation and tutorials.
> Tutorial clean-up

- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Background.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Types.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util.hs
`Electric` code is one of which only one copy should be running at any given moment. This captures the assumption that there is only one chain selection and there is only one process copying stuff to the imm db.
> Implement `Electric` and enclose relevant code

- nix/ghcide-workaround.diff
- nix/shell.nix
https://github.com/haskell/haskell-language-server/issues/4046#issuecomment-1926242056
> Patch HLS 2.6 to work around performance bug

- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup/Classifiers.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup/GenChains.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/LongRangeAttack.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Config.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Tests/Rollback.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Tests/Timeouts.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Trace.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule/Shrinking.hs
- ouroboros-consensus/bench/ChainSync-client-bench/Main.hs
- ouroboros-consensus/bench/mempool-bench/Bench/Consensus/Mempool/TestBlock.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Forecast.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client.hs
- ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/ChainDB.hs
- ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/TestBlock.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/Mempool/Fairness.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/ChainSync/Client.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/LocalStateQuery/Server.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/InMemory.hs
A few notes/questions:
- Do we want the possibility to disable the forecast range?
- Do we want to test with forecast range != genesis window? (If so, with which bounds?)
> Enter finite forecast for test blocks

- .github/workflows/ci.yml
Small change to the GHA workflow so we can inspect test ouput
> Stream test details to stdout in GHA

- ouroboros-consensus-cardano/app/db-analyser.hs
- ouroboros-consensus-cardano/app/db-synthesizer.hs
- ouroboros-consensus-cardano/app/db-truncater.hs
- ouroboros-consensus-cardano/app/immdb-server.hs
- ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
- ouroboros-consensus-cardano/test/cardano-test/Main.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/BlockTree.hs
- ouroboros-consensus/bench/ChainSync-client-bench/Main.hs
- ouroboros-consensus/bench/mempool-bench/Main.hs
- ouroboros-consensus/ouroboros-consensus.cabal
- ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/TestEnv.hs
- scripts/release/create-release.hs
Cherry picking of https://github.com/IntersectMBO/ouroboros-consensus/pull/957 to `genesis/milestone-7-9-10`.
> Ensure UTF-8 support of all terminal handles

- ouroboros-consensus-cardano/src/byron/Ouroboros/Consensus/Byron/Ledger/Ledger.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Ledger.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/SupportsProtocol.hs
- ouroboros-consensus-cardano/src/unstable-cardano-testlib/Test/Consensus/Cardano/Generators.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup/GenChains.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/HardFork/Combinator.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/HardFork/Combinator/A.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/HardFork/Combinator/B.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Block/Abstract.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Genesis/Governor.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Compat.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Ledger.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/History/EraParams.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/History/Qry.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/History/Summary.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Dual.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/SupportsProtocol.hs
- ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/TestBlock.hs
- ouroboros-consensus/src/unstable-mock-block/Ouroboros/Consensus/Mock/Ledger/Block/BFT.hs
- ouroboros-consensus/src/unstable-mock-block/Ouroboros/Consensus/Mock/Ledger/Block/PBFT.hs
- ouroboros-consensus/src/unstable-mock-block/Ouroboros/Consensus/Mock/Ledger/Block/Praos.hs
- ouroboros-consensus/src/unstable-mock-block/Ouroboros/Consensus/Mock/Ledger/Block/PraosRule.hs
- ouroboros-consensus/src/unstable-tutorials/Ouroboros/Consensus/Tutorial/Simple.lhs
- ouroboros-consensus/src/unstable-tutorials/Ouroboros/Consensus/Tutorial/WithEpoch.lhs
- ouroboros-consensus/test/consensus-test/Test/Consensus/HardFork/Infra.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/OnDisk.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/TestBlock.hs
This is both simpler and more general.
The first and third commit are purely mechanical.
> Add a HF `Qry` for the Genesis window, remove `computeGenesisWindow`

- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup.hs
I did check that replacing `forkLinkedThread` by `async` ended up breaking with this new change, reporting
```
*** Failed! Exception: 'FailureSloppyShutdown [Labelled (ThreadId [3]) Nothing,Labelled (ThreadId [5]) Nothing,Labelled (ThreadId [7]) Nothing,Labelled (ThreadId [8]) Nothing,Labelled (ThreadId [9]) Nothing]' (after 1 test):
Exception thrown while showing test case: 'FailureSloppyShutdown [Labelled (ThreadId [3]) Nothing,Labelled (ThreadId [5]) Nothing,Labelled (ThreadId [7]) Nothing,Labelled (ThreadId [8]) Nothing,Labelled (ThreadId [9]) Nothing]'
```
Interestingly, I had to change quite a few `forkLinkedThread` calls before reaching that state.
> Ensure strict termination of all threads in peer simulator

- ouroboros-consensus-protocol/src/unstable-protocol-testlib/Test/Consensus/Protocol/Serialisation/Generators.hs
This file was accidentally deleted.
> UTXO-HD: Fix protocol-tests

- ouroboros-consensus/ouroboros-consensus.cabal
- ouroboros-consensus/test/consensus-test/Test/Consensus/Ledger/Tables/DiffSeq.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/Mempool.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/Mempool/StateMachine.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/BlockFetch/Client.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/ChainSync/Client.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/LocalStateQuery/Server.hs
- completes the merge of consensus-test into `utxo-hd-8.9` and fixes build errors
> Fix consensus-test

- ouroboros-consensus-cardano/changelog.d/20240319_114444_alexander.esgen_era_name.md
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Eras.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Node/Praos.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Node/TPraos.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/ShelleyHFC.hs
> Remove superfluous `shelleyBasedEraName`

- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/API.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Impl/Init.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Impl/Snapshots.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Init.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V2/Args.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V2/Init.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V2/LSM.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/StateMachine.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/StateMachine/TestBlock.hs
> Fix storage-tests again

- ouroboros-consensus-cardano/app/DBAnalyser/Parsers.hs
- ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Analysis.hs
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Block/Cardano.hs
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Run.hs
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Types.hs
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBSynthesizer/Run.hs
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBTruncater/Run.hs
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/ImmDBServer/Diffusion.hs
- ouroboros-consensus-cardano/test/tools-test/Main.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Args.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Impl/Args.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Impl/Init.hs
- ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/ChainDB.hs
> UTXO-HD: fix Cardano tools

- .github/workflows/ci.yml
- docs/website/contents/for-developers/utxo-hd/for-developers.md
- flake.lock
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Analysis.hs
- ouroboros-consensus/bench/backingstore-bench/Main.hs
- ouroboros-consensus/bench/mempool-bench/Bench/Consensus/Mempool/TestBlock.hs
- ouroboros-consensus/bench/mempool-bench/Main.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Basics.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/BackingStore.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V2/Init.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/StateMachine.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/V1/DbChangelog/Unit.hs
Fix the compilation errors in the mempool and backing storage benchmarks.
> Fix mempool and backing storage benchmarks

- CONTRIBUTING.md
- nix/formatting.nix
- nix/shell.nix
- nix/tools.nix
- ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
- ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
- ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
- ouroboros-consensus/ouroboros-consensus.cabal
- scripts/ci/run-cabal-gild.sh
- sop-extras/sop-extras.cabal
- strict-sop-core/strict-sop-core.cabal
- https://taylor.fausak.me/2024/02/17/gild/
- https://github.com/tfausak/cabal-gild
We are mostly interested in this due to the better diffs (no alignment).
> cabal-fmt -> cabal-gild

- cabal.project
- flake.lock
- ouroboros-consensus-diffusion/changelog.d/20240404_233318_coot_peerSharingAPI_fix.md
- ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
- ouroboros-consensus-diffusion/src/unstable-diffusion-testlib/Test/ThreadNet/Network.hs
Get the public peer selection state variable from `Diffusion.Arguments`.
> Integrate with ouroboros-network-0.14.0.0

- .gitignore
- cabal.project
- flake.lock
- ouroboros-consensus/ouroboros-consensus.cabal
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Types.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB.hs
- ouroboros-consensus/test/doctest.hs
- scripts/docs/haddocks.sh
> Add `latex-svg-image` for haddocks

- docs/website/contents/for-developers/ReleaseProcess.md
For comparison, see the recent `cardano-node-8.9-backports` release branch.
> ReleaseProcess: retrofit release/backport branch rules

- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/DensityDisconnect.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Trace.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule/Peers.hs
The test logic failed to ever update the `killed` flag that indicated
that a peer was selected for disconnection before, essentially making
the test tautological.
This revealed the need for another fix – the test must be terminated
when the LOE fragment advances beyond the honest chain (because a branch
forks off the last block).
> Fix prop_densityDisconnectMonotonic

- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Network/NodeToNode.hs
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node/GSM.hs
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/ChainSync.hs
- ouroboros-consensus/ouroboros-consensus.cabal
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client/State.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Node/GsmState.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/LeakyBucket.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/ChainSync/Client.hs
- ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/Util/LeakyBucket/Tests.hs
This PR builds on top of #980 but includes the commits of #975. You might want to read commit-per-commit or you'll also see the changes of the latter.
> Make the LoP follow GSM states

- ouroboros-consensus-diffusion/changelog.d/20240429_143457_alexander.esgen_gsm_remote.md
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
Integrating https://github.com/IntersectMBO/ouroboros-network/pull/4846
Targets #1091
>  GSM: use diffusion layer info for HAA 

- cabal.project
- ouroboros-consensus/changelog.d/orphans-javier.md
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Basics.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Protocol/PBFT.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Protocol/PBFT/Crypto.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/API.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ticked.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/Condense.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/Orphans.hs
Removed `-Wno-orphans` from some modules.
Un-orphan some instances from `Ouroboros.Consensus.Util.Orphans`
Still draft because I need an instance in IntersectMBO/ouroboros-network#4875
> Some orphans work

- cabal.project
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/Orphans.hs
See the single commit's description
> Re-add `ShowProxy SlotNo` orphan instance

- cabal.project
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/Orphans.hs
Reverses https://github.com/IntersectMBO/ouroboros-consensus/pull/1100
> Re-remove ShowProxy SlotNo

- ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node/Genesis.hs
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node/Tracers.hs
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
- ouroboros-consensus-diffusion/src/unstable-diffusion-testlib/Test/ThreadNet/Network.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/NodeLifecycle.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Genesis/Governor.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/API.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Args.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Types.hs
- ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/ChainDB.hs
This integrates the Genesis components in the actual NodeKernel, all behind a feature flag (off by default).
> More GSM integration

- cabal.project
- flake.lock
- ouroboros-consensus-cardano/app/DBAnalyser/Parsers.hs
- ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
- ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/CanHardFork.hs
- ouroboros-consensus-cardano/test/cardano-test/Test/Consensus/Cardano/Translation.hs
- ouroboros-consensus/bench/backingstore-bench/Main.hs
- ouroboros-consensus/bench/mempool-bench/Bench/Consensus/Mempool/TestBlock.hs
- ouroboros-consensus/bench/mempool-bench/Main.hs
- ouroboros-consensus/ouroboros-consensus.cabal
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/State/Types.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Abstract.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Tables/Diff.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Tables/Diffs.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Tables/MapKind.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Tables/Utils.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Impl/Common.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Args.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/BackingStore/Impl/InMemory.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/BackingStore/Impl/LMDB.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/DbChangelog.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Forker.hs
- ouroboros-consensus/test/consensus-test/Main.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/Ledger/Tables/Diff.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/Ledger/Tables/DiffSeq.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/StateMachine.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/V1/BackingStore.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/V1/DbChangelog/Unit.hs
> Use simple diffs except in `DiffSeq`

- .github/workflows/checks.yml
Such that PRs to these release branches can actually pass the required checks.
Cherry-picked from ffe27e6ae1228a6b679d75945fe918a788211609
> GHA: run additional checks in release branches

- .github/workflows/checks.yml
This resolves a common annoyance with stacked PRs.
> GHA: re-run checks on target branch change

- .github/CODEOWNERS
- CHANGELOG.md
- CODEOWNERS
> Add a top-level CHANGELOG and CODEOWNERS files

- flake.lock
- nix/ci.nix
Possible fix for windows cross compilation issue
> Update iserv-proxy pin and enable windows cross compilation

- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/ImmDBServer/MiniProtocols.hs
This fixes a small oversight in the immdb-server ChainSync implementation, as per the [network spec](https://ouroboros-network.cardano.intersectmbo.org/pdfs/network-spec/network-spec.pdf). This isn't actually causing any problems as our ChainSync client isn't relying on this behavior, but there also is no reason not to fix this.
> immdb-server: send rollback after intersection

- ouroboros-consensus/changelog.d/js-tracing-more-snapshot.md
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Snapshots.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/Enclose.hs
Trace a starting event when snapshotting as well as tracing the time spent in snapshotting.
> More verbose tracing when snapshotting

- scripts/ci/run-cabal-gild.sh
- scripts/ci/run-stylish.sh
The path from `pwd` doesn't work, it is a `/c/Users/...` path.
Also using this opportunity to ensure `LF` line endings.
> Fix formatting scripts for MSYS2

- ouroboros-consensus-diffusion/changelog.d/js-trace-unclean.md
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node/Recovery.hs
- ouroboros-consensus/changelog.d/js-trace-unclean.md
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Types.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/StateMachine.hs
> Emit a trace when the DB is not clean

- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Run.hs
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBSynthesizer/Run.hs
- ouroboros-consensus-diffusion/changelog.d/js-flexible-databases.md
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
- ouroboros-consensus/changelog.d/js-flexible-databases.md
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Args.hs
Part of IntersectMBO/cardano-node#5925, only pending integration into the node.
> Allow for different DB paths for immutable and volatile data

- ouroboros-consensus/ouroboros-consensus.cabal
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Dual.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V2/Common.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V2/Init.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/MonadSTM/RAWLock.hs
Closes https://github.com/IntersectMBO/ouroboros-consensus/issues/1193
> RAWLock on the LedgerDB (V2)

- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
> Close forkers when exiting the forging loop early

- ouroboros-consensus-cardano/app/snapshot-converter.hs
- ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Ledger.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/BackingStore/Impl/LMDB.hs
Add the snapshot-converter tool
> Snapshot-converter

- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBSynthesizer/Forging.hs
Now the caller receives a Forker that can be used to obtain (potentially all) values for a ledger state.
> Re-enable tx generator for db synthesizer

- ouroboros-consensus/changelog.d/20241008_190347_alexander.esgen_clock_skew_2_secs.md
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Fragment/InFuture.hs
> Decrease default permissible clock skew to 2s

- ouroboros-consensus-cardano/changelog.d/20241022_125701_alexander.esgen_simplify_praos_params.md
- ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/Node.hs
- ouroboros-consensus-protocol/changelog.d/20241022_125606_alexander.esgen_simplify_praos_params.md
- ouroboros-consensus-protocol/src/ouroboros-consensus-protocol/Ouroboros/Consensus/Protocol/Praos.hs
Noticed while looking at #1285
> Remove unused fields from `PraosParams`

- ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/Node.hs
The NOTE that is removed here was resolved in 26452b2a0c1b05d54ae374cdcd71f2ec92be8aae :tada:
> Correct/clarify comment on initial staking/funds and co

- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs
> ChainSel: slightly tweak sanitizing LoE fragment

- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/StateMachine.hs
Tiny follow-up to #1308, see the commit description
> ChainDB q-s-m: make `loeHasImmutableAnchor` an invariant

- ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/TestBlock.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/BlockFetch/Client.hs
Noticed while doing other stuff, see the commit descriptions
> Two tiny cleanups

- scripts/ci/check-changelogs.sh
Fixes https://github.com/IntersectMBO/ouroboros-consensus/issues/1347
> check-changelogs.sh: bugfix

- cabal.project
`cabal-doctest` has now been fixed
> Remove redundant constraints from cabal.project

- ouroboros-consensus-diffusion/changelog.d/20250203_145928_crocodile-dentist_add_peer_sharing_tracer.md
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Network/NodeToNode.hs
- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
> Add peer sharing tracer

- docs/website/contents/for-developers/Ticking.md
- docs/website/sidebars.js
Adds a document that discusses ticking and how its used within the Consensus Layer.
> docs: draft Ticking.md

- docs/website/contents/for-developers/BlockBlockDiagram.md
- docs/website/sidebars.js
Since I found myself looking this up for the umpteenth time, I paused to document my mental image of the fields within a header and how they all relate to the whole block.
> Draft BlockBlockDiagram.md

- ouroboros-consensus-diffusion/src/unstable-diffusion-testlib/Test/ThreadNet/Util/NodeToNodeVersion.hs
- ouroboros-consensus-diffusion/src/unstable-mock-testlib/Test/ThreadNet/TxGen/Mock.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule/Tests.hs
- ouroboros-consensus-protocol/test/protocol-test/Test/Consensus/Protocol/Praos/SelectView.hs
- ouroboros-consensus/ouroboros-consensus.cabal
- ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/QuickCheck.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/HardFork/Forecast.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/HardFork/Infra.hs
- ouroboros-consensus/test/consensus-test/Test/Consensus/Mempool.hs
- ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/Adversarial.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/StateMachine.hs
- ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/VolatileDB/StateMachine.hs
See the commit description.
"no changelog" label as this only affects tests.
> Remove custom QuickCheck `elements`

- cabal.project
- flake.lock
- ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Analysis/BenchmarkLedgerOps/FileWriting.hs
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Analysis/BenchmarkLedgerOps/SlotDataPoint.hs
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Block/Byron.hs
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Block/Cardano.hs
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Block/Shelley.hs
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/CSV.hs
- ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/HasAnalysis.hs
* Update index-states
* Remove some `allow-newer` stanzas.
> Update index states

- CONTRIBUTING.md
- nix/shell.nix
- nix/tools.nix
In order to be able to easily run in locally to check links
> Add xrefcheck to devShell

- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V2/InMemory.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V2/LedgerSeq.hs
> Remove `isOpen` from `LedgerTablesHandle`

- docs/website/contents/for-developers/TechnicalReports.md
> Add link to `utxo-db-lsm` on the technical reports web page

- README.md
- ouroboros-consensus/CHANGELOG.md
- ouroboros-consensus/changelog.d/20250429_155724_alexander.esgen_follower_forward_bug.md
- ouroboros-consensus/ouroboros-consensus.cabal
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client/Jumping.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Follower.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util.hs
> Release Consensus for Node 10.4.1

- ouroboros-consensus/changelog.d/20250505_133127_alexander.esgen_getledgerconfig_query_debug.md
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Query.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Query/Version.hs
- ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/Serialisation/Roundtrip.hs
> Turn `GetLedgerConfig` into a debug query

- ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
- ouroboros-consensus-cardano/src/byron/Ouroboros/Consensus/Byron/ByronHFC.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Block.hs
- ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Ledger.hs
- ouroboros-consensus-cardano/test/cardano-test/Main.hs
- ouroboros-consensus-cardano/test/cardano-test/Test/Consensus/Cardano/Show.hs
- ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/HardFork/Combinator/A.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/AcrossEras.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Basics.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/PartialConfig.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Dual.hs
Adds a `Show` instance for `HardForkLedgerConfig`
Fixes #1414
> add Show instance for HardForkLedgerConfig

- ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
See the single commit's description
> Remove TODO on only running the GDD with (big) ledger peers

- ouroboros-consensus/changelog.d/20250602_100145_alexander.esgen_small_opts.md
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Follower.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Types.hs
The commits are intended to be reviewed individually, see their commit messages.
No semantic changes.
> ChainDB: minor refactorings/simplifications

- docs/website/contents/for-developers/Glossary.md
- ouroboros-consensus/bench/PerasCertDB-bench/Main.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Block/SupportsPeras.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Peras/Weight.hs
- ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/PerasCertDB/Impl.hs
> Polish Peras weights and weight snapshots

- ouroboros-consensus/changelog.d/20250716_190237_alexander.esgen_tiebreaker_view.md
> Correct changelog entry

- .gitattributes
- docs/website/docusaurus.config.js
- docs/website/package.json
- docs/website/yarn.lock
Re-shaping the documentation broke the UTxO-HD links.
> Set up redirects for UTxO-HD pages

- docs/agda-spec/src/InterfaceLibrary/Common/BaseTypes.agda
- docs/agda-spec/src/InterfaceLibrary/Ledger.lagda
- docs/agda-spec/src/Spec/BaseTypes.lagda
- docs/agda-spec/src/Spec/ChainHead.lagda
- docs/agda-spec/src/Spec/ChainHead/Properties.agda
- docs/agda-spec/src/Spec/Foreign/HSConsensus/ChainHead.agda
- docs/agda-spec/src/Spec/Foreign/HSConsensus/ExternalStructures.agda
- docs/agda-spec/src/Spec/Foreign/HSConsensus/Protocol.agda
- docs/agda-spec/src/Spec/Protocol.lagda
- docs/agda-spec/src/Spec/Protocol/Properties.agda
- docs/agda-spec/src/Spec/hs-src/Lib.hs
- docs/agda-spec/src/Spec/hs-src/test/ChainHeadSpec.hs
- docs/agda-spec/src/Spec/hs-src/test/ProtocolSpec.hs
> Calculate stake proportion in block header spec

- .github/workflows/ci.yml
- nix/haskell.nix
- ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/TestEnv.hs
This small change makes the output of passing ThreadNet tests less verbose by allowing to use `tasty`'s `--hide-successes` CLI option.
With this change, the output of the following test invocation:
```
cabal test -O0 cardano-test --test-options '--hide-successes -p "$2==\"AllegraMary ThreadNet\" && $3==\"simple convergence\""'
```
is still very verbose, but, in my opinion, is relatively readable:
<details>
<summary>Output with Change</summary>
```
Running 1 test suites...
Test suite cardano-test: RUNNING...
All 1 tests passed (34.91s)
Test suite cardano-test: PASS
Test suite logged to:
/home/geo2a/Workspace/IOG/ouroboros-consensus/other-pr/dist-newstyle/build/x86_64-linux/ghc-9.6.7/ouroboros-consensus-cardano-0.25.1.0/t/cardano-test/noopt/test/ouroboros-consensus-cardano-0.25.1.0-cardano-t …
```
> ThreadNet tests: make test output less verbose
